### PR TITLE
Flask webserver & Shell Script

### PR DESCRIPTION
**Pull request by Logan-Fouts**
# Tasks
This project could now easily be run and hosted on a server, EIther I can set it up on my own, you can set it up on yours, or we can use github pages. If we do pages we can make a github actions file that builds it on merge and runs the website. Only annoying thing about that is that some logic for the server would change since pages only really hosts static pages I believe.
## Website
- I used flask to create a simple website that displays csv table and plots if they exist yet.
- This obviously can be changed and whatnot its just a start.
### **TODO:** CSS should be moved out of the html but I was too lazy.
Screenshot from 2024-07-26 12-55-19
## Shell Script
- Created a tiny shell script that automates the task of running the queries then starting the webserver.
- *As of now i have query commented out so we do not run out quickly*
## Requirments.txt
- Froze all new dependencies into the requirments file :+1:

### CODE REVIEW

**Comment by wlauer3** [comment]
I think a lot of the benenfits come from it being in excel, because you do a lot of conditional formatting. but i really like the ui you made. I think we can still use it because the csv can still be downloaded in loaded into excel if desired

**Comment by Logan-Fouts** [comment]
Ah ok I don't really use excel so I'm not aware. 👍

**Comment by wlauer3** [comment]
We could export to an xlsx file instead of csv, then all the calculations would be done outside of our code, if we wanted. and it could be all nice and formatted. I have an example of what it could be like. lemme find it.
[gpu_info.xlsx](https://github.com/user-attachments/files/16392319/gpu_info.xlsx)

You can put in your current card and it highlights slower/faster cards and you can set limits on how much better you would want and it highlights those cards

**Comment by Logan-Fouts** [comment]
Oh ok looks fancy and useful

**Pull request merged**
